version: '3'

services:
  redis1:
    image: redis
    command: redis-server --port 7000
    ports:
      - "7000:7000"
    networks:
      - redis-cluster
    environment:
      - REDIS_CLUSTER_ENABLED=yes
      - REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1

  redis2:
    image: redis
    command: redis-server --port 7001
    ports:
      - "7001:7001"
    networks:
      - redis-cluster
    environment:
      - REDIS_CLUSTER_ENABLED=yes
      - REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1

  redis3:
    image: redis
    command: redis-server --port 7002
    ports:
      - "7002:7002"
    networks:
      - redis-cluster
    environment:
      - REDIS_CLUSTER_ENABLED=yes
      - REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1

networks:
  redis-cluster:
    driver: bridge
